# Generated by Django 5.0.6 on 2024-06-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('piece', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'capteurs',
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.capteur')),
            ],
            options={
                'db_table': 'donnees',
            },
        ),
    ]
