# Generated by Django 5.0.6 on 2024-06-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='id',
        ),
        migrations.AlterField(
            model_name='capteur',
            name='nom',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='piece',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donnee',
            name='capteur',
            field=models.ForeignKey(db_column='capteur_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.capteur'),
        ),
        migrations.AlterField(
            model_name='donnee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='capteur',
            table='capteur',
        ),
        migrations.AlterModelTable(
            name='donnee',
            table='donnee',
        ),
    ]
